"use client";

import { useCallback, useEffect, useState } from "react";
import { RefreshCw } from "lucide-react";
import type { Notification, Payment } from "@/lib/types";
import { EmptyState, ErrorBox, PageTitle, StatusBadge } from "./ui";

const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD" });

export function ActivityView() {
  const [payments, setPayments] = useState<Payment[]>([]);
  const [notifications, setNotifications] = useState<Notification[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");

  const load = useCallback(async () => {
    setLoading(true); setError("");
    try {
      const r = await fetch("/api/activity", { cache: "no-store" });
      if (!r.ok) throw new Error("Could not load event activity.");
      const body = await r.json(); setPayments(body.payments); setNotifications(body.notifications);
    } catch (e) { setError((e as Error).message); }
    finally { setLoading(false); }
  }, []);

  useEffect(() => { void load(); }, [load]);

  return (
    <>
      <PageTitle title="Event activity" subtitle="Observe payment outcomes and the notification side effects produced after Kafka-driven order processing." actions={<button className="btn-secondary flex items-center gap-2" onClick={() => void load()}><RefreshCw size={15} className={loading ? "animate-spin" : ""} /> Refresh</button>} />
      {error && <div className="mb-5"><ErrorBox message={error} /></div>}
      <div className="grid gap-6 xl:grid-cols-2">
        <section className="card p-5"><h2 className="font-bold">Payments</h2><p className="mt-1 text-xs text-slate-500">Generated by payment-service after inventory reservation</p><div className="mt-4 table-wrap">{payments.length ? <table><thead><tr><th>Order</th><th>Status</th><th>Amount</th><th>Reference</th></tr></thead><tbody>{payments.map((p) => <tr key={p.id}><td className="mono text-xs">{p.orderId.slice(0, 10)}…</td><td><StatusBadge value={p.status} /></td><td>{money.format(Number(p.amount))}</td><td className="mono text-xs text-slate-400">{p.providerReference ?? p.failureReason ?? "—"}</td></tr>)}</tbody></table> : <EmptyState>{loading ? "Loading payments…" : "No payment events yet."}</EmptyState>}</div></section>
        <section className="card p-5"><h2 className="font-bold">Notifications</h2><p className="mt-1 text-xs text-slate-500">Recorded by notification-service after order completion/cancellation</p><div className="mt-4 space-y-3">{notifications.length ? notifications.map((n) => <div key={n.id} className="rounded-xl border border-white/10 bg-black/10 p-4"><div className="flex items-center justify-between gap-3"><StatusBadge value={n.type} /><span className="text-xs text-slate-500">{new Date(n.createdAt).toLocaleString()}</span></div><p className="mt-3 text-sm text-slate-300">{n.message}</p><div className="mt-2 mono text-[11px] text-slate-600">{n.orderId}</div></div>) : <EmptyState>{loading ? "Loading notifications…" : "No notifications yet."}</EmptyState>}</div></section>
      </div>
    </>
  );
}
